import * as PIXI from './pixi.js';

export class Objeto {
    constructor(id, nombre, emoji, esObjetivo = false){
        this.id = id
        this.nombre = nombre
        this.emoji = emoji
        this.esObjetivo = esObjetivo
    }
}

export const catálogoObjetos = {
    manzanaRoja: new Objeto('manzanaRoja', 'Manzana roja', '🍎'),
    pezFresco: new Objeto('pezFresco', 'Pez fresco', '🐟'),
    ovilloLana: new Objeto('ovilloLana', 'Ovillo de lana', '🧶'),
    libro: new Objeto('libro', 'Libro', '📕'),
    girasol: new Objeto('girasol', 'Girasol', '🌻'),
    manzanaVerde: new Objeto('manzanaVerde', 'Manzana verde', '🍏'),
    calabaza: new Objeto('calabaza', 'Calabaza', '🎃'),
    panIntegral: new Objeto('panIntegral', 'Pan integral', '🍞'),
    leche: new Objeto('leche', 'Leche', '🥛'),
    queso: new Objeto('queso', 'Queso', '🧀'),
    huevo: new Objeto('huevo', 'Huevo', '🥚'),
    zanahoria: new Objeto('zanahoria', 'Zanahoria', '🥕'),
    peluche: new Objeto('peluche', 'Peluche', '🧸'),
    tomate: new Objeto('tomate', 'Tomate', '🍅'),
    uva: new Objeto('uva', 'Uva', '🍇'),
    sandia: new Objeto('sandia', 'Sandía', '🍉'),
    platano: new Objeto('platano', 'Plátano', '🍌'),
    limon: new Objeto('limon', 'Limón', '🍋'),
    naranja: new Objeto('naranja', 'Naranja', '🍊'),
    fresa: new Objeto('fresa', 'Fresa', '🍓'),
    martillo: new Objeto('martillo', 'Martillo', '🔨'),
    tijeras: new Objeto('tijeras', 'Tijeras', '✂️'),
    lapiz: new Objeto('lapiz', 'Lápiz', '✏️'),
    estrella: new Objeto('estrella', 'Estrella', '⭐'),
    pizza: new Objeto('pizza', 'Pizza', '🍕'),
    gato: new Objeto('gato', 'Gato', '🐱'),
    perro: new Objeto('perro', 'Perro', '🐕'),
    pez: new Objeto('pez', 'Pez', '🐠'),
    cafe: new Objeto('cafe', 'Café', '☕'),
    te: new Objeto('te', 'Té', '🍵'),
    galleta: new Objeto('galleta', 'Galleta', '🍪'),
    pastel: new Objeto('pastel', 'Pastel', '🎂'),
    mate: new Objeto('mate', 'Mate', '🧉'),
    refresco: new Objeto('refresco', 'Refresco', '🥤'),
    miel: new Objeto('miel', 'Miel', '🍯'),
    jugo: new Objeto('jugo', 'Jugo', '🧃'),
    camaron: new Objeto('camaron', 'Camarón', '🦐'),
    pollo: new Objeto('pollo', 'Pollo', '🍗'),
    carne: new Objeto('carne', 'Carne', '🥩'),
    champinon: new Objeto('champinon', 'Champiñón', '🍄'),
    pimiento: new Objeto('pimiento', 'Pimiento', '🫑'),
    maiz: new Objeto('maiz', 'Maíz', '🌽'),
    ajo: new Objeto('ajo', 'Ajo', '🧄'),
    cebolla: new Objeto('cebolla', 'Cebolla', '🧅'),
    papa: new Objeto('papa', 'Papa', '🥔'),
    lechuga: new Objeto('lechuga', 'Lechuga', '🥬'),
    aguacate: new Objeto('aguacate', 'Aguacate', '🥑'),
    pelotaVoley: new Objeto('pelotaVoley', 'Pelota de vóley', '🏐'),
    campana: new Objeto('campana', 'Campana', '🔔'),
    auricular: new Objeto('auricular', 'Auricular', '🎧'),
    trofeo: new Objeto('trofeo', 'Trofeo', '🏆'),
    pelotaFutbol: new Objeto('pelotaFutbol', 'Pelota de fútbol', '⚽'),
    pelotaBasket: new Objeto('pelotaBasket', 'Pelota de básquet', '🏀'),
    raquetaTenis: new Objeto('raquetaTenis', 'Raqueta de tenis', '🎾'),
    guitarra: new Objeto('guitarra', 'Guitarra', '🎸'),
    piano: new Objeto('piano', 'Piano', '🎹'),
    camara: new Objeto('camara', 'Cámara', '📷'),
    telefono: new Objeto('telefono', 'Teléfono', '📱'),
    reloj: new Objeto('reloj', 'Reloj', '⌚'),
    llave: new Objeto('llave', 'Llave', '🔑'),
    bombilla: new Objeto('bombilla', 'Bombilla', '💡'),
    mochila: new Objeto('mochila', 'Mochila', '🎒'),
    sombrero: new Objeto('sombrero', 'Sombrero', '🎩'),
    gafas: new Objeto('gafas', 'Gafas', '👓'),
    paraguas: new Objeto('paraguas', 'Paraguas', '☂️'),
    regalo: new Objeto('regalo', 'Regalo', '🎁'),
    globo: new Objeto('globo', 'Globo', '🎈'),
    dado: new Objeto('dado', 'Dado', '🎲'),
    rompecabezas: new Objeto('rompecabezas', 'Rompecabezas', '🧩'),
    cohete: new Objeto('cohete', 'Cohete', '🚀'),
    avion: new Objeto('avion', 'Avión', '✈️'),
    barco: new Objeto('barco', 'Barco', '⛵'),
    auto: new Objeto('auto', 'Auto', '🚗'),
    bicicleta: new Objeto('bicicleta', 'Bicicleta', '🚲'),
    corona: new Objeto('corona', 'Corona', '👑'),
    diamante: new Objeto('diamante', 'Diamante', '💎'),
    anillo: new Objeto('anillo', 'Anillo', '💍'),
    abeja: new Objeto('abeja', 'Abeja', '🐝'),
    tulipan: new Objeto('tulipan', 'Tulipán', '🌷'),
    rosa: new Objeto('rosa', 'Rosa', '🌹'),
    margarita: new Objeto('margarita', 'Margarita', '🌼'),
    hoja: new Objeto('hoja', 'Hoja', '🍃'),
    arbol: new Objeto('arbol', 'Árbol', '🌳'),
    cactus: new Objeto('cactus', 'Cactus', '🌵'),
    pimientoPicante: new Objeto('pimientoPicante', 'Pimiento picante', '🌶️'),
    despertador: new Objeto('despertador', 'Despertador', '⏰'),
    escoba: new Objeto('escoba', 'Escoba', '🧹'),
    microscopio: new Objeto('microscopio', 'Microscopio', '🔬'),
    telescopio: new Objeto('telescopio', 'Telescopio', '🔭'),
    bandera: new Objeto('bandera', 'Bandera', '🚩'),
    iman: new Objeto('iman', 'Imán', '🧲'),
    cajaHerramientas: new Objeto('cajaHerramientas', 'Caja de herramientas', '🧰'),
    tambor: new Objeto('tambor', 'Tambor', '🥁'),
}

export const obstáculos = []