/** Listas de assets para PIXI y audioManager (sin lógica de carga). */

export const MANIFEST_AUDIO = [
    ['sfx_maullido_1', 'recursos/sonidos/gato1.mp3'],
    ['sfx_maullido_2', 'recursos/sonidos/gato2.mp3'],
    ['sfx_maullido_3', 'recursos/sonidos/gato3.mp3'],
    ['sfx_maullido_4', 'recursos/sonidos/gato4.mp3'],
    ['sfx_maullido_5', 'recursos/sonidos/gato5.mp3'],
    ['sfx_menuApuntado', 'recursos/sonidos/menuApuntado.mp3'],
    ['sfx_menuClickeado', 'recursos/sonidos/menuClickeado.mp3'],
    ['bgm_menu', 'recursos/musica/soundtrackMenu.wav'],
    ['bgm_juego', 'recursos/musica/soundtrackJuego.wav'],
    ['sfx_victoriaComun', 'recursos/sonidos/victoriaComun.mp3'],
    ['sfx_victoriaPrimerPuesto', 'recursos/sonidos/victoriaPrimerPuesto.mp3'],
]

export const FUENTE_UI = {
    alias: 'Perfect',
    src: 'recursos/fuentePixelart.ttf',
}

export const MANIFEST_SPRITES = [
    'recursos/sprites/jugador.json',
    'recursos/sprites/gato_gris.json',
    'recursos/sprites/gato_negro.json',
    'recursos/sprites/gato_blanco.json',
    'recursos/sprites/gato_violeta.json',
    'recursos/sprites/gato_naranja.json',
    'recursos/sprites/shiro.json',
    'recursos/sprites/shiro.png',
    'recursos/sprites/afro.json',
    'recursos/sprites/afro.png',
    'recursos/sprites/accesorios.png',
    'recursos/sprites/pastito.png',
    'recursos/sprites/comercio1.png',
    'recursos/sprites/comercio2.png',
    'recursos/sprites/comercio3.png',
    'recursos/sprites/arbol1.png',
    'recursos/sprites/arbol2.png',
    'recursos/sprites/arbol3.png',
    'recursos/sprites/arbol4.png',
    'recursos/sprites/picnic.png',
    'recursos/sprites/banquito1.png',
    'recursos/sprites/items.png',
    'recursos/sprites/objetivo_temporizador.png',
    'recursos/sprites/panel.png',
    'recursos/sprites/intercambio_item.png',
    'recursos/sprites/globo.png',
    'recursos/sprites/patita_prota.png',
    'recursos/sprites/accesorios.json',
    'recursos/sprites/ganaste.png',
    'recursos/sprites/fondoMenu.png',
    'recursos/sprites/boton1.png',
    'recursos/sprites/boton1_seleccionado.png',
    'recursos/sprites/titulo_gatimercado.png',
    'Perfect',
    'recursos/sprites/mariposa_roja.png',
    'recursos/sprites/mariposa_rosa.png',
    'recursos/sprites/mariposa_verde.png',
    'recursos/sprites/mariposa_violeta.png',
    'recursos/sprites/sapito_amarillo.png',
    'recursos/sprites/sapito_gris.png',
    'recursos/sprites/sapito_naranja.png',
    'recursos/sprites/sapito_verde.png',
    'recursos/sprites/boton2.png',
    'recursos/sprites/boton_largo1.png',
    'recursos/sprites/boton2_seleccionado.png',
]
